const $=s=>document.querySelector(s);
function status(text,error=false){$('#login-status').textContent=text;$('#login-status').dataset.error=String(error);}
async function request(path,body){const r=await fetch(path,{method:body?'POST':'GET',cache:'no-store',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(12000)});const b=await r.json();if(!r.ok)throw new Error(b.error||'No se pudo ingresar.');return b;}
try{const s=await request('api/session');if(s.editor)location.replace('editor.html');$('#login-local').hidden=!s.local;$('#login-submit').disabled=!s.configured;status(s.configured?'':'El acceso está pendiente de configuración.');}catch{status('No se pudo conectar con el servicio. Volvé a intentar.',true);}
$('#login-show').onclick=e=>{const show=$('#login-password').type==='password';$('#login-password').type=show?'text':'password';e.target.textContent=show?'Ocultar':'Mostrar';e.target.setAttribute('aria-pressed',String(show));e.target.setAttribute('aria-label',show?'Ocultar contraseña':'Mostrar contraseña');};
$('#login-form').onsubmit=async e=>{e.preventDefault();$('#login-submit').disabled=true;status('Ingresando…');try{const result=await request('api/auth/login',{email:$('#login-email').value,password:$('#login-password').value});$('#login-password').value='';if(result.mfa){$('#login-form').hidden=true;$('#login-mfa').hidden=false;$('#login-code').focus();status('Completá la verificación para continuar.');}else location.replace('editor.html');}catch(e){status(e.message,true);$('#login-password').value='';$('#login-password').focus();}finally{$('#login-submit').disabled=false;}};
$('#login-demo').onclick=async()=>{try{await request('api/auth/local',{});location.replace('editor.html');}catch(e){status(e.message,true);}};

$('#login-mfa').onsubmit=async e=>{e.preventDefault();$('#mfa-submit').disabled=true;status('Verificando…');try{await request('api/auth/mfa',{code:$('#login-code').value});location.replace('editor.html');}catch(e){status(e.message,true);$('#login-code').value='';$('#login-code').focus();}finally{$('#mfa-submit').disabled=false;}};
