import test from 'node:test';
import assert from 'node:assert/strict';
import {api} from '../server/api.js';
import {abrirDB} from '../server/sqlite.js';
import {headersSeguridad} from '../server/http.js';
import {hash} from '../server/auth.js';
const origin='https://mapa.example.org';
function setup(){const DB=abrirDB(':memory:');let calls=0,valid=true;const env={DB,SUPABASE_URL:'https://test.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public-test',SESSION_ENCRYPTION_KEY:'ab'.repeat(32),EDITOR_EMAILS:'modeloonulp@gmail.com',AUTH_FETCH:async(url,init)=>{calls++;if(!valid)return new Response('{}',{status:401});const user={id:'user-123',email:'modeloonulp@gmail.com',email_confirmed_at:'2026-01-01'};return new Response(JSON.stringify(url.endsWith('/user')?user:{access_token:'TOKEN-PRIVADO-NO-EXPOSICION',refresh_token:'NO-GUARDAR',expires_in:3600,user}));}};return{env,DB,setValid(v){valid=v;},calls:()=>calls,async call(path,method='GET',value,headers={}){return api(new Request(origin+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...headers},body:value?JSON.stringify(value):undefined}),env);}};}
async function login(h){const r=await h.call('/api/auth/login','POST',{email:'modeloonulp@gmail.com',password:'solo-prueba'});assert.equal(r.status,200);return r.headers.get('set-cookie');}
test('login: cookie opaca, HttpOnly, Secure, SameSite; tokens cifrados y sin refresh token',async()=>{const h=setup();try{const cookie=await login(h);assert.match(cookie,/^__Host-mapa_session=[a-f0-9]{64};/);assert.match(cookie,/HttpOnly/);assert.match(cookie,/SameSite=Strict/);assert.match(cookie,/; Secure/);assert.doesNotMatch(cookie,/TOKEN|refresh/);const row=await h.DB.prepare('SELECT * FROM sesiones').first();assert.notEqual(row.hash,cookie.split('=')[1].split(';')[0]);assert.doesNotMatch(row.token,/TOKEN|NO-GUARDAR/);const r=await h.call('/api/session','GET',null,{Cookie:cookie});assert.equal((await r.json()).editor,true);}finally{h.DB.close();}});
test('logout revoca la sesión de inmediato y cookie manipulada no autentica',async()=>{const h=setup();try{const cookie=await login(h);assert.equal((await h.call('/api/draft','GET',null,{Cookie:cookie.replace(/[a-f0-9]{64}/,'0'.repeat(64))})).status,401);await h.call('/api/auth/logout','POST',{}, {Cookie:cookie});assert.equal((await h.call('/api/draft','GET',null,{Cookie:cookie})).status,401);}finally{h.DB.close();}});
test('sesión vencida, proveedor revocado y usuario fuera de allowlist no escriben',async()=>{const h=setup();try{const cookie=await login(h);h.env.EDITOR_EMAILS='otra@example.org';assert.equal((await h.call('/api/draft','GET',null,{Cookie:cookie})).status,401);h.env.EDITOR_EMAILS='modeloonulp@gmail.com';h.setValid(false);assert.equal((await h.call('/api/draft','GET',null,{Cookie:cookie})).status,401);h.setValid(true);await h.DB.prepare('UPDATE sesiones SET vence=0').run();assert.equal((await h.call('/api/draft','GET',null,{Cookie:cookie})).status,401);}finally{h.DB.close();}});
test('headers falsificados y modo local no habilitan acceso en producción',async()=>{const h=setup();try{h.env.LOCAL_USER='admin';h.env.AUTH_MODE='sites';const r=await h.call('/api/draft','GET',null,{'oai-authenticated-user-id':'admin','oai-authenticated-user-email':'modeloonulp@gmail.com'});assert.equal(r.status,401);assert.equal((await h.call('/api/auth/local','POST',{})).status,404);}finally{h.DB.close();}});
test('CSRF en login, logout y publicaciones se rechaza',async()=>{const h=setup();try{const cookie=await login(h);for(const path of ['/api/auth/login','/api/auth/logout','/api/publish']){assert.equal((await h.call(path,'POST',{email:'modeloonulp@gmail.com',password:'x'},{Cookie:cookie,Origin:'https://atacante.example'})).status,403);}}finally{h.DB.close();}});
test('fuerza bruta limitada por cuenta y entradas grandes rechazadas',async()=>{const h=setup();try{for(let i=0;i<5;i++)await h.call('/api/auth/login','POST',{email:'modeloonulp@gmail.com',password:'x'});assert.equal((await h.call('/api/auth/login','POST',{email:'modeloonulp@gmail.com',password:'x'})).status,429);assert.equal(h.calls(),5);assert.equal((await h.call('/api/auth/login','POST',{email:'x@example.org',password:'x'.repeat(3000)})).status,413);}finally{h.DB.close();}});
test('cabeceras bloquean ejecución inline, framing, sniffing y envío de referrer',()=>{const req=new Request(origin);const r=headersSeguridad(new Response('<html>'),req);assert.match(r.headers.get('content-security-policy'),/script-src 'self';/);assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.equal(r.headers.get('referrer-policy'),'no-referrer');assert.equal(r.headers.get('x-content-type-options'),'nosniff');assert.ok(r.headers.has('strict-transport-security'));});
test('MFA pendiente no autentica; TOTP eleva sesión y el desafío no se reutiliza',async()=>{
 const h=setup();const user={id:'user-123',email:'modeloonulp@gmail.com',email_confirmed_at:'2026-01-01',factors:[{id:'factor-1',status:'verified',factor_type:'totp'}]};
 const jwt=aal=>'header.'+Buffer.from(JSON.stringify({aal})).toString('base64url')+'.signature';let elevated=false;
 h.env.AUTH_FETCH=async(url,init)=>{if(url.endsWith('/challenge'))return Response.json({id:'challenge-1'});if(url.endsWith('/verify')){const b=JSON.parse(init.body);assert.equal(b.challenge_id,'challenge-1');if(b.code!=='123456')return Response.json({}, {status:400});elevated=true;return Response.json({access_token:jwt('aal2'),expires_in:3600,user});}if(url.endsWith('/user'))return Response.json(user);return Response.json({access_token:jwt('aal1'),expires_in:3600,user});};
 try{const r=await h.call('/api/auth/login','POST',{email:user.email,password:'x'});assert.equal((await r.json()).mfa,true);const pending=r.headers.get('set-cookie');assert.equal((await h.call('/api/draft','GET',null,{Cookie:pending})).status,401);assert.equal((await h.call('/api/auth/mfa','POST',{code:'000000'},{Cookie:pending})).status,401);assert.equal(elevated,false);
 const verified=await h.call('/api/auth/mfa','POST',{code:'123456'},{Cookie:pending});assert.equal(verified.status,200);assert.equal((await h.call('/api/session','GET',null,{Cookie:verified.headers.get('set-cookie')})).status,200);assert.equal((await (await h.call('/api/session','GET',null,{Cookie:verified.headers.get('set-cookie')})).json()).editor,true);assert.equal((await h.call('/api/auth/mfa','POST',{code:'123456'},{Cookie:pending})).status,401);
 }finally{h.DB.close();}
});
test('activar MFA invalida acceso de primer factor existente',async()=>{const h=setup();try{const cookie=await login(h);h.env.AUTH_FETCH=async()=>Response.json({id:'user-123',email:'modeloonulp@gmail.com',email_confirmed_at:'2026-01-01',factors:[{id:'factor-1',status:'verified',factor_type:'totp'}]});assert.equal((await h.call('/api/draft','GET',null,{Cookie:cookie})).status,401);}finally{h.DB.close();}});
